# Generated by Django 2.2.6 on 2019-10-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20191030_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
