# Generated by Django 2.2.6 on 2019-11-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='46e556bc4f4549a6b5825527bbbc7242e7da2ec63b2e449e8c08c300112098f8', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='11f05045043a4d4a809209ffa747624a1e775493c6c7458c9ef4b6b24e0014aa', max_length=300, null=True),
        ),
    ]
