# Generated by Django 2.2.6 on 2019-11-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191110_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='c6013b9734144a9ea751d75630e6dcb56e68e6d6533840ab81f624689150b09d', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='2fc315c8cc6245b79987afd3dba455144af7077d499043f1abac25d8af2e9a4a', max_length=300, null=True),
        ),
    ]
