# Generated by Django 2.2.6 on 2019-11-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191111_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='d223b5810bb246b7b7263e4259a55fc756c0590f3805456ca2cba4870c4ff731', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='744a11174c9a4414b10991415d9e16daf77b372f0b9c450988aea4ff95664e55', max_length=300, null=True),
        ),
    ]
