# Generated by Django 2.2.6 on 2019-11-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191111_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='bb02101517dc479e895a11852105e94b8ee7c650444247858268887d0f1a1d1c', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='dccde05e3ee542be99b352640e6456a91c333c47dfbb4fe3828ea9b21a4c464b', max_length=300, null=True),
        ),
    ]
