# Generated by Django 2.2.6 on 2019-10-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='dishes.Dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drinks',
            field=models.ManyToManyField(blank=True, to='dishes.Drink'),
        ),
    ]
